// frontend/src/pages/About.tsx
import Header from "../components/Header.tsx";
import Footer from "../components/Footer.tsx";

import lex_png from "../assets/about/lex.png";
import clarrise_png from "../assets/about/clarrise.png";
import annabelle_png from "../assets/about/annabelle.png";
import ravindu_png from "../assets/about/ravindu.png";
import allyson_png from "../assets/about/allyson.png";
import ellie_png from "../assets/about/ellie.png";
import nikolay_png from "../assets/about/nikolay.png";
import killian_png from "../assets/about/killian.png";

import {onMount} from "solid-js";
import {animate, createTimeline, onScroll, stagger, utils} from "animejs";
import kiwanis from "../assets/about/kiwanis.jpg";

const About = () => {
    onMount(() => {
        document.title = "About"
        utils.set(".pnw-bg", {
            transformOrigin: "center left",
            scaleX: "100%"
        })
        utils.set(".kc-bg", {
            transformOrigin: "center left",
            scaleX: "100%"
        })

        animate(".section-1", {
            backgroundColor: "#000000",
            ease: "outSine",
            autoplay: onScroll({
                // debug: true,
                target: ".section-1",
                enter: "top top",
                leave: "top 25vh",
                sync: true,
                repeat: false
            })
        })
        animate(".intro-text", {
            color: "#FFFFFF",
            ease: "outSine",
            autoplay: onScroll({
                // debug: true,
                target: ".section-1",
                enter: "top top",
                leave: "top 25vh",
                sync: true,
                repeat: false
            })
        })


        utils.set(".cards", {
            x: "-18rem"
        })
        utils.set(".cards-info", {
            x: "-100%"
        })

        utils.$(".cards").forEach((card) => {
            const timeline = createTimeline({
                autoplay: false,
                defaults: {
                    ease: "outQuad",
                    duration: 1000,
                }
            });
            timeline.add(card, {
                x: "2rem"
            }, 0)
            timeline.add(card.querySelectorAll(".cards-info"), {
                x: "0%",
                delay: stagger(250)
            }, 400)

            onScroll({
                // debug: true,
                target: card,
                enter: "center top",
                onEnter: () => timeline.play()
            })
        })
    })

    const animate_button = (start: boolean, bg: string) => {
        animate(bg, {
            transformOrigin: "center left",
            scaleX: start ? 0 : 1,
            duration: 300,
            ease: "outQuad",
        })
    }

    return (
        <>
            <Header/>

            <section class={"section-1 w-full h-fit text-white"}>
                <div class="relative spacer w-full h-[75vh] flex flex-col items-center justify-center text-center">
                    <header class={"intro-text text-black text-7xl"}>MEET THE OFFICERS</header>
                    <h1 class="intro-text text-black mt-[2rem]">(scroll)</h1>
                </div>
                <section class="space-y-[10rem] mx-auto w-fit pr-[3rem] overflow-hidden">

                    <div class="cards w-fit h-fit] flex">
                        <div class="p-[1rem] bg-white z-10">
                            <img class={"size-[16rem]"} src={lex_png} alt="Lex Padua"/>
                        </div>
                        <div class={"w-fit ml-[1rem] overflow-hidden"}>
                            <h1 class="cards-info text-5xl! font-semibold">President</h1>
                            <h1 class="cards-info">Lex Padua</h1>
                            <h1 class="cards-info text-xl!">alexmariepadua19@gmail.com</h1>
                        </div>
                    </div>

                    <div class="cards w-fit h-fit] flex">
                        <div class="p-[1rem] bg-white z-10">
                            <img class={"size-[16rem]"} src={clarrise_png} alt="Lex Padua"/>
                        </div>
                        <div class={"w-fit ml-[1rem] overflow-hidden"}>
                            <h1 class="cards-info text-5xl! font-semibold">Vice President</h1>
                            <h1 class="cards-info">Clarrise Song</h1>
                            <h1 class="cards-info text-xl!">clarissesong18@gmail.com</h1>
                        </div>
                    </div>

                    <div class="cards w-fit h-fit] flex">
                        <div class="p-[1rem] bg-white z-10">
                            <img class={"size-[16rem]"} src={annabelle_png} alt="Annabelle Ho"/>
                        </div>
                        <div class={"w-fit ml-[1rem] overflow-hidden"}>
                            <h1 class="cards-info text-5xl! font-semibold">Treasurer</h1>
                            <h1 class="cards-info">Annabelle Ho</h1>
                            <h1 class="cards-info text-xl!">annabelle.zt.ho@gmail.com</h1>
                        </div>
                    </div>

                    <div class="cards w-fit h-fit] flex">
                        <div class="p-[1rem] bg-white z-10">
                            <img class={"size-[16rem]"} src={ravindu_png} alt="Ravindu Marasinghe"/>
                        </div>
                        <div class={"w-fit ml-[1rem] overflow-hidden"}>
                            <h1 class="cards-info text-5xl! font-semibold">Secretary</h1>
                            <h1 class="cards-info">Ravindu Marasinghe</h1>
                            <h1 class="cards-info text-xl!">ravindu2008@icloud.com</h1>
                        </div>
                    </div>

                    <div class="cards w-fit h-fit] flex">
                        <div class="p-[1rem] bg-white z-10">
                            <img class={"size-[16rem]"} src={allyson_png} alt="Allyson Chun"/>
                        </div>
                        <div class={"w-fit ml-[1rem] overflow-hidden"}>
                            <h1 class="cards-info text-5xl! font-semibold">Editor</h1>
                            <h1 class="cards-info">Allyson Chun</h1>
                            <h1 class="cards-info text-xl!">allysonhw96@gmail.com</h1>
                        </div>
                    </div>

                    <div class="cards w-fit h-fit] flex">
                        <div class="p-[1rem] bg-white z-10">
                            <img class={"size-[16rem]"} src={ellie_png} alt="Ellie Nguyen"/>
                        </div>
                        <div class={"w-fit ml-[1rem] overflow-hidden"}>
                            <h1 class="cards-info text-5xl! font-semibold">Editor</h1>
                            <h1 class="cards-info">Ellie Nguyen</h1>
                            <h1 class="cards-info text-xl!">ellienguyen882@gmail.com</h1>
                        </div>
                    </div>

                    <div class="cards w-fit h-fit] flex">
                        <div class="p-[1rem] bg-white z-10">
                            <img class={"size-[16rem]"} src={nikolay_png} alt="Nikolay Li"/>
                        </div>
                        <div class={"w-fit ml-[1rem] overflow-hidden"}>
                            <h1 class="cards-info text-5xl! font-semibold">Webmaster</h1>
                            <h1 class="cards-info">Nikolay Li</h1>
                            <h1 class="cards-info text-xl!">nikolay.li2008@gmail.com</h1>
                        </div>
                    </div>

                    <div class="cards w-fit h-fit] flex">
                        <div class="p-[1rem] bg-white z-10">
                            <img class={"size-[16rem]"} src={killian_png} alt="Killian Bates"/>
                        </div>
                        <div class={"w-fit ml-[1rem] overflow-hidden"}>
                            <h1 class="cards-info text-5xl! font-semibold">Secretary</h1>
                            <h1 class="cards-info">Killian Bates</h1>
                            <h1 class="cards-info text-xl!">killianj1010@outlook.com</h1>
                        </div>
                    </div>
                </section>
            </section>
            <div class="relative w-full h-[75vh] bg-black"/>

            <section class={"w-full h-screen p-[2rem] flex flex-col"}>
                <section class={"grid grid-cols-3"}>
                    <div class={"relative flex flex-col"}>
                        <header class={"mx-auto text-3xl"}>
                            Faculty Advisors
                        </header>

                        <div class={"mx-auto mt-[.5rem]"}>
                            <h1 class={"text-2xl!"}>
                                Alfred Cain
                            </h1>
                            <h1 class={"text-lg!"}>
                                acain@everettsd.org
                            </h1>
                            <h1 class={"text-2xl!"}>
                                Rachel Vaught
                            </h1>
                            <h1 class={"text-lg!"}>
                                rvaught@everettsd.org
                            </h1>
                        </div>

                        <div class={"absolute right-[1rem] inset-y-0 my-auto h-3/4 w-0 border-1"}></div>
                    </div>

                    <div class={"flex flex-col"}>
                        <header class={"text-center mx-auto text-3xl"}>
                            Division 21 Lieutenant Governor
                        </header>

                        <div class={"mx-auto mt-[.5rem]"}>
                            <h1 class={"text-2xl!"}>
                                Maeve Hershlip
                            </h1>
                            <h1 class={"text-lg!"}>
                                ltg21@pnwkeyclub.org
                            </h1>
                        </div>
                    </div>

                    <div class={"relative flex flex-col"}>
                        <header class={"mx-auto text-3xl"}>
                            Kiwanis Advisors
                        </header>

                        <div class={"mx-auto mt-[.5rem]"}>
                            <h1 class={"text-2xl!"}>
                                John Steckler
                            </h1>
                            <h1 class={"text-lg!"}>
                                johnsteckler@comcast.net
                            </h1>
                            <h1 class={"text-2xl!"}>
                                Lisa Steckler
                            </h1>
                            <h1 class={"text-lg!"}>
                                stecklerlisa@gmail.com
                            </h1>
                        </div>

                        <div class={"absolute left-[1rem] inset-y-0 my-auto h-3/4 w-0 border-1"}></div>
                    </div>
                </section>

                <header class={"text-6xl my-[2rem] text-center"}>OUR PARTNERS & PREFERRED CHARITIES</header>
                <section class="flex-1">
                    <div class="bg-black h-full w-full lg:w-[60%] mx-auto"></div>
                </section>
            </section>

            <section class={"w-full h-screen flex"}>
                <div class={"w-1/2 p-[2rem] flex items-center justify-center"}>
                    <div class={"text-center flex flex-col items-center justify-center"}>
                        <header class="text-6xl">
                            OUR KIWANIS
                        </header>
                        <h1 class="mt-8 w-full xl:w-[75%]">
                            JHS Key Club is sponsored by the Kiwanis of Mill Creek.
                            Kiwanis is an international community of clubs in which is dedicated to serving the
                            community and the lives of the children around it.
                        </h1>

                        <a class={"p-[1rem] bg-black text-white text-xl my-[1rem]"} href="https://www.kiwanis.org/">
                            Learn More About Kiwanis
                        </a>

                        <a class={"p-[1rem] bg-[#0866ff] text-white text-xl"} href="https://www.facebook.com/Kiwanisofmillcreek/">
                            Mill Creek Kiwanis Facebook
                        </a>
                    </div>
                </div>
                <img class={"w-1/2 h-full object-cover"} src={kiwanis} alt="Mill Creek Kiwanis"/>
            </section>

            <section class="w-full p-[2rem] text-center">
                <header class={"text-6xl"}>MORE WEBSITES</header>
                <h1 class={"mt-[1rem] mb-[2rem]"}>Check out our district websites to learn more or catch up with the
                    buzz!</h1>

                <div class="flex text-white text-4xl mx-auto w-fit space-x-[2rem]">
                    <a
                        onmouseenter={() => animate_button(true, ".kc-bg")}
                        onmouseleave={() => animate_button(false, ".kc-bg")}
                        class="relative w-fit h-fit p-[2rem] hover:no-underline!"
                        href={"https://www.keyclub.org/"}
                        target={"_blank"}>
                        <h1 class={"text-black-outline z-20 hover:no-underline!"}>Key Club</h1>
                        <div class={"kc-bg absolute -z-10 top-0 left-0 w-full h-full object-cover bg-black"}/>
                        <img class={"absolute -z-20 top-0 left-0 w-full h-full object-contain text-shadow"}
                             src="https://ktkey.org/wp-content/uploads/Template_KeyClub_Blue-key-graphic.jpg.jpg"
                             alt="Key Club"/>
                    </a>

                    <a
                        onmouseenter={() => animate_button(true, ".pnw-bg")}
                        onmouseleave={() => animate_button(false, ".pnw-bg")}
                        class="relative w-fit h-fit p-[2rem] hover:no-underline!"
                        href={"https://pnwkeyclub.org/"}
                        target={"_blank"}>
                        <h1 class={"hover:no-underline!"}>PNW Key Club</h1>
                        <div class={"pnw-bg absolute -z-10 top-0 left-0 w-full h-full object-cover bg-black"}/>
                        <img class={"absolute -z-20 top-0 left-0 w-full h-full object-cover"}
                             src="https://i.natgeofe.com/n/1ac29c4c-43b5-41d5-8db4-668370f3cdaa/GettyImages-1130537468.gif"
                             alt="PNW Key Club"/>
                    </a>
                </div>
            </section>
            <Footer/>
        </>
    )
}

export default About

// frontend/src/routes/about/+page.svelte
<script>
    import gsap from "gsap";
    import ScrollTrigger from "gsap/ScrollTrigger";
    import {horizontalLoop} from "$lib/HorizontalLoop.js";
    import Header from "$lib/components/Header.svelte";
    import Footer from "$lib/components/Footer.svelte";
    import ResponsiveButton from "$lib/components/ResponsiveButton.svelte";
    import Icon from "@iconify/svelte"
    import {onMount} from "svelte";

    let loop
    let officer_section
    const partner_change = {duration: .8, ease: "power2.out"}
    let can_send = $state(true)
    let small = $state(false)
    let fbsrc = $state("")

    onMount(() => {
        document.title = "About"
        gsap.registerPlugin(ScrollTrigger)

        fbsrc = "https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FKiwanisofmillcreek&tabs=timeline&width=340&height=500"

        gsap.to(officer_section, {
            backgroundColor: "#231f20",
            scrollTrigger: {
                trigger: officer_section,
                start: "top top",
                end: () => "+=" + 1/4 * innerHeight, // end after quarter of screen height
                scrub: 1,
                once: true,
                // markers: true,
            }
        })
        gsap.to(".intro-text", {
            color: "#fed450",
            scrollTrigger: {
                trigger: officer_section,
                start: "top top",
                end: () => "+=" + 1/4 * innerHeight,
                scrub: 1,
                once: true,
                // markers: true,
            }
        })

        small = innerWidth < 768
        // if larger than md
        if (!small) {
            gsap.set(".cards-info", {
                xPercent: -100
            })
        } else {
            gsap.set(".cards-info-stack", {
                yPercent: -100
            })
        }
        gsap.set(".cards", {
            xPercent: -110
        })

        gsap.utils.toArray(".cards").forEach((card) => {
            const card_st = ScrollTrigger.create({
                trigger: card,
                start: small ? "top 40%" : "top 60%",
                // markers: true
            })

            gsap.to(card, {
                xPercent: 0,
                duration: .3,
                ease: "power2.out",
                scrollTrigger: card_st
            })
            if (!small) {
                gsap.to(card.querySelectorAll(".cards-info"), {
                    xPercent: 0,
                    stagger: .2,
                    duration: .3,
                    ease: "power2.out",
                    delay: .2,
                    scrollTrigger: card_st
                })
            } else {
                gsap.to(card.querySelectorAll(".cards-info-stack"), {
                    yPercent: 0,
                    stagger: .2,
                    duration: .3,
                    ease: "power2.out",
                    delay: .2,
                    scrollTrigger: card_st
                })
            }
        })


        const partners = gsap.utils.toArray(".partner")
        let active_element
        loop = horizontalLoop(partners, {
            paused: true,
            draggable: false,
            center: true,
            onChange: (element) => { // when the active element changes, this function gets called.
                active_element && active_element.classList.remove("active");
                element.classList.add("active");
                active_element = element;
            }
        })

        setInterval(() => {
            loop.next({duration: 1, ease: "power2.out"});
        }, 10 * 1000)

        return () => ScrollTrigger.getAll().forEach((trigger) => trigger.kill())
    })
</script>

<Header/>
<section bind:this={officer_section} class="w-full h-fit text-white">
    <div class="w-full h-[75vh] flex flex-col items-center justify-center text-center">
        <header class="intro-text text-black text-7xl">MEET THE OFFICERS</header>
<!--        <h1 class="intro-text text-black mt-8">(scroll)</h1>-->
    </div>
    <section class="space-y-[14rem] py-[10rem] w-[80%] md:w-fit mx-auto overflow-hidden">

        <div class="relative cards h-fit w-full md:flex">
            <img class="relative w-full md:size-[20rem] aspect-square border-kcyellow border-16 z-10"
                 src="/about/lex.png"
                 alt="Lex Padua"/>
            <div class="cards-info-stack absolute left-0 md:relative w-fit ml-4 overflow-hidden">
                <div class={"h-4 w-full"}></div>
                <h1 class="cards-info text-5xl text-kcyellow font-[century-gothic-bold]">President</h1>
                <h1 class="cards-info text-3xl mt-2">Lex Padua</h1>
                <h1 class="cards-info text-lg flex items-center text-gray-400"><Icon icon="fe:mail" /><span
                        class="ml-2">alexmariepadua19@gmail.com</span></h1>
            </div>
        </div>

        <div class="relative cards h-fit w-full md:flex">
            <img class="relative w-full md:size-[20rem] aspect-square border-kcyellow border-16 z-10"
                 src="/about/clarrise.png" alt="Clarrise Song"/>
            <div class="cards-info-stack absolute left-0 md:relative w-fit ml-4 overflow-hidden">
                <div class="h-4 w-full"></div>
                <h1 class="cards-info text-5xl text-kcyellow font-[century-gothic-bold]">Vice President</h1>
                <h1 class="cards-info text-3xl mt-2">Clarrise Song</h1>
                <h1 class="cards-info text-xl flex items-center text-gray-400"><Icon icon="fe:mail" /><span
                        class="ml-2">clarissesong18@gmail.com</span></h1>
            </div>
        </div>

        <div class="relative cards h-fit w-full md:w-fit md:flex">
            <img class="relative w-full md:size-[20rem] aspect-square border-kcyellow border-16 z-10"
                 src="/about/annabelle.png" alt="Annabelle Ho"/>
            <div class="cards-info-stack absolute left-0 md:relative w-fit ml-4 overflow-hidden">
                <div class="h-4 w-full"></div>
                <h1 class="cards-info text-5xl text-kcyellow font-[century-gothic-bold]">Treasurer</h1>
                <h1 class="cards-info text-3xl mt-2">Annabelle Ho</h1>
                <h1 class="cards-info text-xl flex items-center text-gray-400"><Icon icon="fe:mail" /><span
                        class="ml-2">annabelle.zt.ho@gmail.com</span></h1>
            </div>
        </div>

        <div class="relative cards h-fit w-full md:w-fit md:flex">
            <img class="relative w-full md:size-[20rem] aspect-square border-kcyellow border-16 z-10"
                 src="/about/ravindu.png" alt="Ravindu Marasinghe"/>
            <div class="cards-info-stack absolute left-0 md:relative w-fit ml-4 overflow-hidden">
                <div class="h-4 w-full"></div>
                <h1 class="cards-info text-5xl text-kcyellow font-[century-gothic-bold]">Secretary</h1>
                <h1 class="cards-info text-3xl mt-2">Ravindu Marasinghe</h1>
                <h1 class="cards-info text-xl flex items-center text-gray-400"><Icon icon="fe:mail" /><span
                        class="ml-2">ravindu2008@icloud.com</span></h1>
            </div>
        </div>

        <div class="relative cards h-fit w-full md:w-fit md:flex">
            <img class="relative w-full md:size-[20rem] aspect-square border-kcyellow border-16 z-10"
                 src="/about/allyson.png" alt="Allyson Chun"/>
            <div class="cards-info-stack absolute left-0 md:relative w-fit ml-4 overflow-hidden">
                <div class="h-4 w-full"></div>
                <h1 class="cards-info text-5xl text-kcyellow font-[century-gothic-bold]">Editor</h1>
                <h1 class="cards-info text-3xl mt-2">Allyson Chun</h1>
                <h1 class="cards-info text-xl flex items-center text-gray-400"><Icon icon="fe:mail" /><span
                        class="ml-2">allysonhw96@gmail.com</span></h1>
            </div>
        </div>

        <div class="relative cards h-fit w-full md:w-fit md:flex">
            <img class="relative w-full md:size-[20rem] aspect-square border-kcyellow border-16 z-10"
                 src="/about/ellie.png" alt="Ellie Nguyen"/>
            <div class="cards-info-stack absolute left-0 md:relative w-fit ml-4 overflow-hidden">
                <div class="h-4 w-full"></div>
                <h1 class="cards-info text-5xl text-kcyellow font-[century-gothic-bold]">Editor</h1>
                <h1 class="cards-info text-3xl mt-2">Ellie Nguyen</h1>
                <h1 class="cards-info text-xl flex items-center text-gray-400"><Icon icon="fe:mail" /><span
                        class="ml-2">ellienguyen882@gmail.com</span></h1>
            </div>
        </div>
        <div class="relative cards h-fit w-full md:w-fit md:flex">
            <img class="relative w-full md:size-[20rem] aspect-square border-kcyellow border-16 z-10"
                 src="/about/nikolay.png" alt="Nikolay Li"/>
            <div class="cards-info-stack absolute left-0 md:relative w-fit ml-4 overflow-hidden">
                <div class="h-4 w-full"></div>
                <h1 class="cards-info text-5xl text-kcyellow font-[century-gothic-bold] pr-1">Webmaster</h1>
                <h1 class="cards-info text-3xl mt-2">Nikolay Li</h1>
                <h1 class="cards-info text-xl flex items-center text-gray-400"><Icon icon="fe:mail" /><span
                        class="ml-2">youdontneed@my.email</span></h1>
            </div>
        </div>
        <div class="relative cards h-fit w-full md:w-fit md:flex">
            <img class="relative w-full md:size-[20rem] aspect-square border-kcyellow border-16 z-10"
                 src="/about/killian.png" alt="Killian Bates"/>
            <div class="cards-info-stack absolute left-0 md:relative w-fit ml-4 overflow-hidden">
                <div class="h-4 w-full"></div>
                <h1 class="cards-info text-5xl text-kcyellow font-[century-gothic-bold]">Secretary</h1>
                <h1 class="cards-info text-3xl mt-2">Killian Bates</h1>
                <h1 class="cards-info text-xl flex items-center text-gray-400"><Icon icon="fe:mail" /><span
                        class="ml-2">killianj1010@outlook.com</span></h1>
            </div>
        </div>

    </section>
</section>

<section class="w-full min-h-screen p-8 flex items-center flex-col text-center">
    <header class="text-6xl sm:text-7xl mb-4">FACULTY ADVISORS</header>

    <div class="grid grid-cols-1 sm:grid-cols-2 gap-[4rem] w-[90%] lg:w-[70%] xl:w-[60%] flex-1">

        <div class="flex flex-col h-full w-full items-center justify-center">
            <img class="object-cover border-kcyellow border-16 aspect-[3/4] w-full" src="/about/mrcain.png"
                 alt="Mr. Cain"/>
            <h1 class="font-[century-gothic-bold] text-5xl mt-4">Alfred Cain</h1>
            <h1 class="text-2xl flex items-center text-gray-600"><Icon icon="fe:mail" /><span class="ml-2">
                            acain@everettsd.org</span></h1>
        </div>

        <div class="flex flex-col h-full w-full items-center justify-center">
            <img class="object-cover border-kcyellow border-16 aspect-[3/4] w-full"
                 src="/about/mrsvaught.jpeg"
                 alt="Mrs. Vaught"/>
            <h1 class="font-[century-gothic-bold] text-5xl mt-4">Rachel Vaught</h1>
            <h1 class="text-2xl flex items-center text-gray-600"><Icon icon="fe:mail" /><span class="ml-2">
                            rvaught@everettsd.org</span></h1>
        </div>

    </div>
</section>

<section class="w-full min-h-screen p-8 flex items-center flex-col text-center">
    <header class="text-6xl sm:text-7xl mb-4">KIWANIS ADVISORS</header>

    <div class="grid grid-cols-1 sm:grid-cols-2 gap-[4rem] w-[90%] lg:w-[70%] xl:w-[60%] flex-1">

        <div class="flex flex-col h-full w-full items-center justify-center">
            <img class="object-cover border-kcyellow border-16 aspect-[3/4] w-full"
                 src="/about/mrsteckler.png"
                 alt="Mr. Cain"/>
            <h1 class="font-[century-gothic-bold] text-5xl mt-4">John Steckler</h1>
            <h1 class="text-2xl flex items-center text-gray-600"><Icon icon="fe:mail" /><span class="ml-2">
                            johnsteckler@comcast.net</span></h1>
        </div>

        <div class="flex flex-col h-full w-full items-center justify-center">
            <img class="object-cover border-kcyellow border-16 aspect-[3/4] w-full"
                 src="/about/mrssteckler.png"
                 alt="Mrs. Vaught"/>
            <h1 class="font-[century-gothic-bold] text-5xl mt-4">Lisa Steckler</h1>
            <h1 class="text-2xl flex items-center text-gray-600"><Icon icon="fe:mail" /><span class="ml-2">
                            stecklerlisa@gmail.com</span></h1>
        </div>

    </div>
</section>

<section class="w-full min-h-screen p-8 flex items-center flex-col text-center">
    <header class="text-6xl sm:text-7xl mb-4">D21 LIEUTENANT GOVERNOR</header>

    <div
            class="w-[90%] sm:w-[50%] lg:w-[35%] xl:w-[30%] flex-1 flex flex-col items-center justify-center">
        <img class="object-cover border-kcyellow border-16 h-[90%] aspect-[3/4] w-full"
             src="/about/maeve.jpg"
             alt="Maeve"/>
        <h1 class="font-[century-gothic-bold] text-5xl mt-4">Maeve Hershlip</h1>
        <h1 class="text-2xl flex items-center text-gray-600"><Icon icon="fe:mail" /><span class="ml-2">
                            ltg21@pnwkeyclub.org</span></h1>
    </div>
</section>

<section class="w-full h-screen p-8 flex items-center flex-col text-white">
    <header class="text-4xl sm:text-7xl text-black text-center">OUR PREFERRED PARTNERS AND CHARITIES</header>

    <div
            class="border-16 border-kcyellow mt-8 w-full h-[80%] md:h-[70%] md:aspect-[1.2] lg:w-auto lg:aspect-[1.7] flex overflow-hidden">

        <div class="partner relative w-full h-full flex-none">
            <div class="absolute p-8 h-full z-10">
                <img class="h-[20%] object-contain" src="/about/thirstproject_logo.png" alt="Logo"/>

                <h1 class="text-md sm:text-xl mt-8 sm:leading-10">
                    Thirst Project hopes to educate the next generation by arming students with
                    information
                    about how they can be a part of social change,
                    make a difference and encourage others to join in the effort.

                    <a class="float-right text-black bg-white mt-4 p-4 text-xl"
                       href="https://thirstproject.org/" target="_blank">Learn More</a>
                </h1>
            </div>

            <img class="object-cover z-0 w-full h-full" src="/about/thirstproject.png" alt="Thirst Project"/>
        </div>

        <div class="partner relative w-full h-full flex-none">
            <div class="absolute p-8 h-full z-10">
                <img class="h-[20%] object-contain" src="/about/unicef_logo.png" alt="Logo"/>

                <h1 class="text-md md:text-xl mt-8 sm:leading-6">
                    UNICEF is the only organization of the United Nations dedicated exclusively to
                    children.
                    Working with other United Nations bodies, governments and non-governmental
                    organizations,
                    UNICEF helps to provide for children’s needs in more than 150 developing countries
                    through community-based services in primary health care,
                    basic education and safe water and sanitation.

                    <a class="float-right text-black bg-white mt-4 p-4 text-xl"
                       href="https://www.unicef.org/" target="_blank">Learn More</a>
                </h1>
            </div>

            <img class="object-cover z-0 w-full h-full" src="/about/unicef.jpg" alt="Unicef"/>
        </div>

        <div class="partner relative w-full h-full flex-none">
            <div class="absolute p-8 h-full z-10">
                <img class="h-[20%] object-contain" src="/about/erikaslighthouse_logo.png" alt="Logo"/>

                <h1 class="text-md md:text-xl mt-8 sm:leading-6">
                    The mission of Erika's Lighthouse is to make sure no young person feels alone in
                    their depression.
                    This nonprofit organization encourages good mental health and strives to break down
                    the stigma surrounding mental health issues.
                    Erika's Lighthouse is dedicated to creating a community of empathy and education and
                    has resources and programs for students and educators, grades 4-12.

                    <a class="float-right text-black bg-white mt-4 p-4 text-xl"
                       href="https://erikaslighthouse.org/" target="_blank">Learn More</a>
                </h1>
            </div>

            <img class="object-cover brightness-[.2] z-0 w-full h-full" src="/about/erikaslighthouse.jpeg"
                 alt="Erika's Lighthouse"/>
        </div>

        <div class="partner relative w-full h-full flex-none">
            <div class="absolute p-8 h-full z-10">
                <img class="h-[20%] object-contain" src="/about/schoolhouse_logo.png" alt="Logo"/>

                <h1 class="text-md md:text-xl mt-8 sm:leading-6">
                    Want to make an impact and have fun while doing it? Looking for a service project
                    that you can complete from the comfort of your bedroom?
                    Key Club has partnered with Schoolhouse to bring free tutoring to thousands of
                    learners across the world.
                    If you're interested in learning something new, or you're interested in becoming a
                    tutor yourself, sign up today!

                    <a class="float-right text-black bg-white mt-4 p-4 text-xl"
                       href="https://schoolhouse.world/key-club" target="_blank">Learn More</a>
                </h1>
            </div>

            <img class="object-cover brightness-[1.2] z-0 w-full h-full" src="/about/schoolhouse.png"
                 alt="schoolhouse"/>
        </div>

        <div class="partner relative w-full h-full flex-none">
            <div class="absolute p-8 h-full z-10">
                <img class="h-[20%] object-contain" src="/about/collegewise_logo.png" alt="Logo"/>

                <h1 class="text-md md:text-xl mt-8 sm:leading-6">
                    Collegewise helps identify the college that’s right for you, assists with the
                    application process,
                    and provides tutoring for ACT/SAT exams. While a paid subscription is available for
                    those who wish to access it,
                    every Key Club member has access to a suite of Collegewise resources on the Runway
                    platform as a member benefit.

                    <a class="float-right text-black bg-white mt-4 p-4 text-xl"
                       href="https://collegewise.com/" target="_blank">Learn More</a>
                </h1>
            </div>

            <img class="object-cover z-0 w-full h-full" src="/about/collegewise.jpg" alt="Collegewise"/>
        </div>

    </div>

    <div class="flex text-black gap-8 mt-4">
        <button onclick={() => loop.previous(partner_change)}>
            <Icon icon="solar:arrow-left-outline" class="size-[4rem]"/>
        </button>
        <button onclick={() => loop.next(partner_change)}>
            <Icon icon="solar:arrow-right-outline" class="size-[4rem]"/>
        </button>
    </div>
</section>

<section class="w-full h-screen grid grid-cols-1 grid-rows-2 md:grid-cols-2 md:grid-rows-1">
    <div class="w-full h-full flex flex-col items-center justify-center p-8">
        <header class="text-4xl md:text-7xl">OUR KIWANIS</header>
        <h1 class="text-3xl md:text-2xl mt-8 text-left">
            JHS Key Club is sponsored by the Kiwanis of Mill Creek.
            Kiwanis is an international community of clubs in which is dedicated to serving the
            community and the lives of the children around it.
        </h1>
    </div>
    <img class="w-full h-full object-cover" src="/about/kiwanis.jpg" alt="Mill Creek Kiwanis"/>
</section>

<section class="w-full p-8 my-[4rem] text-center">
    <header class="text-4xl sm:text-7xl">MORE WEBSITES</header>
    <h1 class="mt-4 mb-8 text-3xl text-left">
        Check out our international and district websites to learn more or catch up with the buzz!
    </h1>

    <div class="flex flex-col md:flex-row mx-auto text-4xl space-x-8">
        <ResponsiveButton bg_color="kcpink" init_text="Key Club" clicked_text="..." on_click={() => window.open("https://keyclub.org/", "_blank")} can_send={can_send}/>
        <ResponsiveButton init_text="PNW Key Club" clicked_text="..." on_click={() => window.open("https://pnwkeyclub.org/", "_blank")} can_send={can_send}/>
    </div>
</section>
<Footer/>
