// frontend/src/routes/membership/+page.svelte
<script>
    import SplitText from "gsap/SplitText";
    import gsap from "gsap";
    import {onMount} from "svelte";
    import Header from "$lib/components/Header.svelte";
    import Footer from "$lib/components/Footer.svelte";

    let htext

    onMount(() => {
        document.title = "Membership"

        const headerText = SplitText.create(htext).words

        gsap.fromTo(headerText, {
            yPercent: 50,
            opacity: 0,
        }, {
            yPercent: 0,
            opacity: 1,
            stagger: 1/5,
            duration: .5,
            delay: .5,
            ease: "power2.out",
        })
    })
</script>

<Header/>
<section class="w-full min-h-screen text-center text-2xl">
    <div class="relative w-full h-[30vh] flex flex-col items-center justify-center">
        <header bind:this={htext} class="text-white text-4xl">
            REGISTRATION IS CLOSED
        </header>
        <img class="absolute -z-10 top-0 left-0 w-full h-full object-cover" src="/membership/membership_cover.jpg"
             alt="Membership Cover"/>
    </div>

    <section class="p-4 space-y-8 md:space-y-16 w-full my-8 md:text-3xl">

        <div class="w-full grid grid-cols-1 grid-rows-2 md:grid-cols-2 md:grid-rows-1">
            <img class="object-contain w-[80%] mx-auto" src="/membership/members1.png" alt="Members 1"/>
            <div class="w-full">
                <header class="text-4xl mb-8">Be a Keyutie</header>
                <p class="text-left ">
                    <span class="underline">Get an ASB card!</span> If you don't already have one, go to the
                    ASB office for assistance.
                    <br/><br/>
                    Start your service!
                    <br/><br/>
                    Participate in club events/socials, go to DCMs, and attend club
                    meetings. Requirements are listed below.
                </p>
            </div>
        </div>

        <div class="w-full grid grid-cols-1 grid-rows-2 md:grid-cols-2 md:grid-rows-1">
            <img class="md:order-2 object-contain w-[80%] mx-auto" src="/membership/members2.png" alt="Members 2"/>
            <div class="md:order-1 w-full">
                <header class="text-4xl mb-8">Pay Dues</header>
                <p class="text-left">
                    The official dues payments are closed.
                    <br/><br/>
                    Check back next year!
                </p>
            </div>
        </div>

        <div class="w-full grid grid-cols-1 grid-rows-2 md:grid-cols-2 md:grid-rows-1">
            <img class="object-contain w-[80%] mx-auto" src="/membership/members3.png" alt="Members 3"/>
            <div class="w-full">
                <header class="text-4xl mb-8">Stay in the Hive</header>
                <p class="text-left">
                    Complete your annual hour requirement of <span class="underline">25 hours</span>!
                    <br/><br/>
                    Attend <span class="underline">50%</span> of the general meetings.
                    <br/><br/>
                    Attend all events you've signed up for. Give a <span
                        class="underline">24 hour notice</span> if you can't make it to an
                    event.
                    Misbehavior or failure to show up to 3 events without advanced notice gets you suspended
                    from Key Club.
                </p>
            </div>
        </div>

    </section>
</section>
<Footer/>

// frontend/src/pages/Membership.tsx
import {onMount} from "solid-js";
import {Header} from "../components/Header.tsx";
import {Footer} from "../components/Footer.tsx";
import membeship_cover from "../assets/membership/membership_cover.jpg";
import members_1 from "../assets/membership/members1.png";
import members_2 from "../assets/membership/members2.png";
import members_3 from "../assets/membership/members3.png";

export const Membership = () => {
    onMount(() => document.title = "Membership")

    return (
        <>
            <Header/>
            <section class={"w-full min-h-screen  text-center"}>
                <div class={"relative w-full h-[30rem] flex flex-col items-center justify-center"}>
                    <header class={"text-white text-7xl"}>
                        REGISTRATION IS OPEN
                    </header>
                    <img class={"absolute -z-10 top-0 left-0 w-full h-full object-cover"} src={membeship_cover}
                         alt="Membership Cover"/>
                </div>

                <section class="flex flex-col lg:flex-row p-[4rem] justify-center">
                    <img class={"hidden lg:block object-contain mb-0 lg:w-[40%] mx-auto"} src={members_1}
                         alt="Members 1"/>
                    <div class={"flex flex-col items-center justify-center px-[4rem]"}>
                        <header class={"text-6xl mb-[2rem]"}>Be a Keyutie</header>
                        <h1>
                            Get an ASB card! If you don't already have one, go to the ASB office for assistance.
                            Start your service! Participate in club events/socials, go to DCMs, and attend club
                            meetings. Requirements are listed below.
                        </h1>
                    </div>
                    <img class={"block lg:hidden object-contain mt-[2rem] w-[80%] mx-auto"} src={members_1}
                         alt="Members 1"/>
                </section>

                <section class="flex flex-col lg:flex-row p-[4rem] justify-center">
                    <div class={"flex flex-col items-center justify-center px-[4rem]"}>
                        <header class={"text-6xl mb-[2rem]"}>Pay Dues</header>
                        <h1>
                            The official dues payments are closed.
                            <br/>
                            Check back next year!
                        </h1>
                    </div>
                    <img class={"object-contain mt-[2rem] lg:mt-0 w-[80%] lg:w-[40%] mx-auto"} src={members_2} alt="Members 2"/>
                </section>

                <section class="flex flex-col lg:flex-row p-[4rem] justify-center">
                    <img class={"hidden lg:block object-contain mb-0 lg:w-[40%] mx-auto"} src={members_3}
                         alt="Members 3"/>
                    <div class={"flex flex-col items-center justify-center px-[4rem]"}>
                        <header class={"text-6xl mb-[2rem]"}>Stay in the Hive!</header>
                        <h1>
                            Complete your annual hour requirement of 25 hours!
                            <br/><br/>
                            Attend 50% of the general meetings (exceptions for sports apply).
                            <br/><br/>
                            Attend all events you've signed up for. Give a 24 hour notice if you can't make it to an
                            event.
                            Misbehavior or failure to show up to 3 events without advanced notice gets you suspended
                            from Key Club.
                        </h1>
                    </div>
                    <img class={"block lg:hidden object-contain mt-[2rem] w-[80%] my-auto mx-auto"} src={members_3}
                         alt="Members 3"/>
                </section>
            </section>
            <Footer/>
        </>
    )
}
