// frontend/src/components/Header.jsx
import {createEffect, createSignal, onCleanup, onMount} from "solid-js";
import {FiArrowDown} from "solid-icons/fi";
import {A} from "@solidjs/router"
import gsap from "gsap";

export const Header = () => {
    const [open, set_open] = createSignal(false)
    let menu_height

    onMount(() => {
        menu_height = document.querySelector(".menu").offsetHeight
        addEventListener("click", (event) => handle_click_outside(event))
    })

    onCleanup(() => removeEventListener("click", (event) => handle_click_outside(event)))

    createEffect(() => {
        gsap.to(".menu", {
            y: open() ? menu_height: 0,
            duration: .4,
            boxShadow: open() ? "0px 20px 25px -5px rgba(0, 0, 0, .3)" : "0px 0px 0px 0px rgba(0, 0, 0, 0)",
            ease: "power2.out"
        })
    })

    const handle_click_outside = (event) => {
        if (open() && !document.querySelector(".menu").contains(event.target) && !document.querySelector(".menu-button").contains(event.target)) {
            set_open(false)
        }
    }

    return (
        <>
            <section class={"relative header w-full z-30"}>
                <div class={"relative w-full h-full top-0 left-0 z-30 p-4 flex flex-col items-center bg-white"}>
                    <a class={"mb-2"} href={"/"}>
                        <img class={"h-[4rem] object-contain"} src="/keyclub_horizontal_black.png" alt="Key Club Logo"/>
                        <h1 class={"text-4xl text-gray-600"}>Henry M. Jackson High School</h1>
                    </a>

                    <ul class={"hidden lg:flex lg:space-x-8 xl:space-x-16 items-center mt-6 text-2xl"}>
                        <A class={"hover:underline"} href="/">Home</A>
                        <A class={"hover:underline"} href="/about">About</A>
                        <A class={"hover:underline"} href="/events">Events</A>
                        <A class={"hover:underline"} href="/districtproject">District Project</A>
                        <A class={"hover:underline"} href="/membership">Membership</A>
                        <A class={"hover:underline"} href="/gallery">Gallery</A>
                        <A class={"hover:underline"} href="/contact">Contact Us</A>
                    </ul>

                    <button onclick={() => set_open(true)}
                            class={"menu-button my-auto lg:hidden w-fit p-1 rounded-xl border-1"}
                    >
                        <FiArrowDown
                            class={"size-[2rem]"}
                        />
                    </button>
                </div>

                <div class="absolute bg-white w-full h-full top-0 left-0 z-20"/>

                <section class={"menu absolute bottom-0 flex-none inset-x-0 w-fit mx-auto z-0 bg-white p-8 rounded-b-2xl z-10"}>
                    <ul class={"flex flex-col space-y-4 items-center text-4xl"}>
                        <A class={"hover:underline"} href="/">Home</A>
                        <A class={"hover:underline"} href="/about">About</A>
                        <A class={"hover:underline"} href="/events">Events</A>
                        <A class={"hover:underline"} href="/districtproject">District Project</A>
                        <A class={"hover:underline"} href="/membership">Membership</A>
                        <A class={"hover:underline"} href="/gallery">Gallery</A>
                        <A class={"hover:underline"} href="/contact">Contact Us</A>
                    </ul>
                </section>
            </section>
        </>
    )
}

// src/lib/components/Header.svelte
<script>
    import gsap from "gsap";
    import {onMount} from "svelte";

    let menu
    let menuButton
    let menuOpen = $state(false)
    let windowClickHandler

    onMount(() => {
        gsap.set(menu, {
            transformOrigin: "top left",
            xPercent: 100
        })
        windowClickHandler = (event) => handleClickOutside(event)
        addEventListener("click", windowClickHandler)
        return () => removeEventListener("click", windowClickHandler)
    })

    $effect(() => {
        console.log("open/close")
        gsap.to(menu, {
            xPercent: menuOpen ? -100 : 0,
            duration: .3,
            ease: "power2.out"
        })
    })

    // if a user clicks and the menu and menu button don't contain the click, close the menu
    const handleClickOutside = (event) => {
        if (menuOpen && !menu.contains(event.target) && !menuButton.contains(event.target)) {
            menuOpen = false
        }
    }
</script>

<section class="relative flex flex-col w-full h-27.5 md:h-45 z-30 text-kcblack bg-stone-200 p-4 items-center"
         style="box-shadow: 0px 5px 5px 5px hsl(0 1% 30% / .1)">
    <a class="w-[80%] md:w-auto max-h-full md:h-[80%] self-start md:self-auto" href="/"><img class="h-full object-contain" src="/keyclub_horizontal_black.png" alt="Key Club Logo"/></a>
    <button class="block md:hidden" bind:this={menuButton} onclick={() => menuOpen = !menuOpen} aria-label="Menu button">
        <svg class="absolute right-3 top-2" xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24"><path fill="currentColor" d="M4 18q-.425 0-.712-.288T3 17t.288-.712T4 16h16q.425 0 .713.288T21 17t-.288.713T20 18zm0-5q-.425 0-.712-.288T3 12t.288-.712T4 11h16q.425 0 .713.288T21 12t-.288.713T20 13zm0-5q-.425 0-.712-.288T3 7t.288-.712T4 6h16q.425 0 .713.288T21 7t-.288.713T20 8z"/></svg>
    </button>

    <ul class="hidden md:flex w-full xl:w-[80%] text-xl xl:text-2xl items-center justify-between">
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/events">Events</a></li>
        <li><a href="/membership">Membership</a></li>
        <li><a href="/districtproject">District Project</a></li>
    </ul>
</section>

<section
    bind:this={menu}
    class="fixed flex flex-col right-0 top-0 z-20 w-[70%] h-screen bg-stone-200 p-4"
    style="transform: translateX(100%);"
>
    <div class="spacer w-full h-27.5"></div>
    <ul class="text-kcblack text-3xl space-y-2">
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/events">Events</a></li>
        <li><a href="/membership">Membership</a></li>
        <li><a href="/districtproject">District Project</a></li>
    </ul>
    <div class="spacer flex-1"></div>
    <img class="object-contain w-32 h-32 mx-auto" src="/bee.webp" alt="Wolfbee">
</section>
